# -*- coding: utf-8 -*-
# Generated by Django 1.11.3 on 2017-08-28 10:58
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('photoshare', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='instapost',
            name='url',
            field=models.CharField(default='http://ilefthogwarts.pythonanywhere.com', max_length=100),
        ),
    ]
