# -*- coding: utf-8 -*-
# Generated by Django 1.11.3 on 2017-08-28 13:35
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('photoshare', '0003_auto_20170828_1406'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='instapost',
            name='description',
        ),
        migrations.RemoveField(
            model_name='instapost',
            name='user_name',
        ),
        migrations.RemoveField(
            model_name='user',
            name='user_post',
        ),
    ]
