# -*- coding: utf-8 -*-
# Generated by Django 1.11.3 on 2017-08-28 13:47
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('photoshare', '0004_auto_20170828_1635'),
    ]

    operations = [
        migrations.AddField(
            model_name='instapost',
            name='user_post',
            field=models.ForeignKey(default=None, on_delete=django.db.models.deletion.DO_NOTHING, to='photoshare.User'),
        ),
    ]
