# -*- coding: utf-8 -*-
# Generated by Django 1.11.3 on 2017-08-30 07:26
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('photoshare', '0006_posttags'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='instapost',
            name='tag',
        ),
    ]
