# -*- coding: utf-8 -*-
# Generated by Django 1.11.3 on 2017-08-30 09:17
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('photoshare', '0007_remove_instapost_tag'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='posttags',
            name='taged_post',
        ),
        migrations.AddField(
            model_name='instapost',
            name='tag',
            field=models.ManyToManyField(to='photoshare.PostTags'),
        ),
    ]
